import { Metadata } from "next";
import './globals.css'
import Header from './components/Header'
import ErrorWrapper from "./error-wrapper";


export const metadata: Metadata = {
  title: {
    default: "Next.js App",
    template: "%s | Manish",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body>
        <Header />
        <ErrorWrapper>{children}</ErrorWrapper> 
        <footer style={{ background: "ghostwhite", padding: '1rem' }}>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
