import { Metadata } from "next";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MarketingLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body>
        <header style={{ background: "lightred", padding: '1rem' }}>
          <p>Header</p>
        </header>
        
        {children}
        <footer style={{ background: "ghostwhite", padding: '1rem' }}>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
